# Generated by Django 3.2 on 2021-04-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='cid',
            new_name='class_id',
        ),
    ]
